### ISSUE TITLE
Inconsistent CMake versions in use

### ISSUE THREAD

**Issue by foundry-markf** [markfinal/cruiz#165]
I am launching cruiz as 'python -m cruiz' on Windows. From a cmd shell (no VS version) and an virtual environment with CMake 3.29.6 installed.

I need 3.29 for certain features.

But, although the cruiz UI is picking up 3.29, the build is using 3.27 from VisualStudio 2022, which is unexpected as it should not be pathd in, other than via finding the compiler.

![image](https://github.com/user-attachments/assets/21c8b4e4-b07e-4275-b6e9-1c2649313134)

Same behaviour when launched as `cruiz`.

**Comment by foundry-markf** [comment]
If I use a VS2022 command prompt, the issue goes away.

**Comment by markfinal** [comment]
Attempted to recreate this on a fresh Windows 11 x86_64 install, with VS2022, CMake 3.31, and Windows Terminal.

Checking in Process Explorer, a build using CMake was using the CMake in the virtual environment.

Closing until a time when there are reproducible steps.
