### ISSUE TITLE
Bug: enabling hooks in Conan 1 errors

### ISSUE THREAD

**Issue by foundry-markf** [markfinal/cruiz#168]
This was an attempt after enabling a custom hook in the Manage Local Caches dialog

```
WARN: Hook 'indowsPath('banana.py' not found in C:\dev\recipes\.conan\hooks folder. Please remove hook from conan.conf or include it inside the hooks folder.
```

That looks suspiciously like passing the path to the hook should not be using a `pathlib.Path`.

**Comment by foundry-markf** [comment]
I saw this in the local cache conan.conf
```
[hooks]
attribute_checker
indowsPath('banana.py
```

**Comment by foundry-markf** [comment]
So it looks like passing a pathlib.Path into ConanHook (a dataclass), and using the from_string class method fails to do the right thing for Windows paths.

Paths are sourced in _hooks_item_changed in managelocalcachesdialog.py.

Commands run on the data in _hooks_sync in meta.py.

ConanHook defined in interop/pod.py

**Comment by markfinal** [comment]
I also replicated this in macOS

```
osixPath('banana.py
```

in the preferences file.
