### ISSUE TITLE
Bug: enabling hooks does not persist the checkbox

### ISSUE THREAD

**Issue by foundry-markf** [markfinal/cruiz#169]
If I check a new hook

![image](https://github.com/user-attachments/assets/a4b3870e-1812-49a8-8aa6-c73136fbddc1)

and then press Apply, the checkbox disappears

![image](https://github.com/user-attachments/assets/5005e17c-c8b7-44a2-bb16-c9a0b2bdd359)

**Comment by foundry-markf** [comment]
I don't see anything in preferences.ini, either after Apply or OK is pressed in the dialog.

**Comment by markfinal** [comment]
Confirmed this on the latest code in main on macOS.

**Comment by markfinal** [comment]
It seems to be tightly coupled with https://github.com/markfinal/cruiz/issues/168

**Comment by markfinal** [comment]
Also fixed
