### ISSUE TITLE
Support recipes without a version and without a conandata.yml

### ISSUE THREAD

**Issue by foundry-markf** [markfinal/cruiz#83]
For example, this could be a recipe for a package whose version is procedural from a source control tag.

Suggestion:
- if a recipe has a version attribute, use that, else
- if a conandata.yml, offer a choice of those present (assuming it's parsable), else
- provide ability to enter a version number

**Comment by markfinal** [comment]
This is what you currently see when there is no version attribute and no conandata.yml

![Screenshot 2023-07-13 at 20 04 42](https://github.com/markfinal/cruiz/assets/984489/e92f0469-dbd2-4ef8-b667-8262eff4f55a)
